### ISSUE TITLE
DSJ 182 Beach 113th St - Bug Showing Negative Water Use

### ISSUE THREAD

**Issue by jaredlbs** [livebuildingsystems/livebuildings-issues#4]
Looking at DSJ Management, 182 Beach 113th Street on Sept 4th there is a water consumption of -40,731 gallons.

Can we get this fixed?
https://livebuildings.com/buildings/182-beach-113th-street-1220/water?start=2017-09-03&end=2017-09-09

https://mail.google.com/mail/u/0/?ui=2&ik=62dbfe11af&view=fimg&th=15e75f4cbf53e4ef&attid=0.1&disp=emb&realattid=ii_15e75f35146cf3df&attbid=ANGjdJ-lmhVMJXhyxPVnvf7gQbPQsiHWCcZoS-pMjcZY-sNn6MImbaJyItcgOVkBFHvL7FHuEGSzd74z2z4nEBUq1I7KVHqS2tBmmJGHWNaHnSOpg4BDxV5X0GaUiuc&sz=w710-h788&ats=1505233779522&rm=15e75f4cbf53e4ef&zw&atsh=1

DEP WEBSITE - login DSJmgt5 /DSJmgt5
https://mail.google.com/mail/u/0/?ui=2&ik=62dbfe11af&view=fimg&th=15e75f4cbf53e4ef&attid=0.2&disp=emb&realattid=ii_15e75f43f0d70b11&attbid=ANGjdJ8bGRjheEYHc3wI9FT6-cPgojuW4WHk1hFm2MLS9xXH_zYjX_PRruwPhJmGUrZwkuky2bBNKHDO5jvW7Kppdoh9T-LYxymVZdUtGgGmuUyXRKYkAPM_yU_GmCU&sz=w788-h750&ats=1505233779522&rm=15e75f4cbf53e4ef&zw&atsh=1

**Comment by markdegroat** [comment]
From email with Shane:

Negative Value Water Fixed (emailed)
The negative value on DSJ 182 Beach 113th St was fixed. It was something to do with a non value set on the DEP site which made our db confused. Will make a note to try to prevent this bug.
